"""
utils/code_executor.py
Safely executes Python engineering code generated by the AI.
Supports NumPy, SciPy, SymPy, matplotlib for math/simulation.
"""

import sys
import io
import traceback
import contextlib
import matplotlib
import matplotlib.pyplot as plt
import base64

# Use non-interactive backend for Streamlit compatibility
matplotlib.use("Agg")


# Allowed imports for the sandboxed environment
SAFE_GLOBALS = {
    "__builtins__": {
        "print": print,
        "range": range,
        "len": len,
        "list": list,
        "dict": dict,
        "tuple": tuple,
        "set": set,
        "abs": abs,
        "round": round,
        "min": min,
        "max": max,
        "sum": sum,
        "sorted": sorted,
        "enumerate": enumerate,
        "zip": zip,
        "map": map,
        "filter": filter,
        "isinstance": isinstance,
        "type": type,
        "str": str,
        "int": int,
        "float": float,
        "complex": complex,
        "bool": bool,
        "True": True,
        "False": False,
        "None": None,
    }
}

def _build_exec_globals():
    """Build the execution namespace with engineering libraries."""
    exec_globals = dict(SAFE_GLOBALS)
    exec_globals["__builtins__"] = SAFE_GLOBALS["__builtins__"]

    try:
        import numpy as np
        exec_globals["np"] = np
        exec_globals["numpy"] = np
    except ImportError:
        pass

    try:
        import scipy
        import scipy.signal as signal
        import scipy.linalg as linalg
        import scipy.optimize as optimize
        exec_globals["scipy"] = scipy
        exec_globals["signal"] = signal
        exec_globals["linalg"] = linalg
        exec_globals["optimize"] = optimize
    except ImportError:
        pass

    try:
        import sympy as sp
        exec_globals["sp"] = sp
        exec_globals["sympy"] = sp
    except ImportError:
        pass

    try:
        import matplotlib.pyplot as plt
        exec_globals["plt"] = plt
        exec_globals["matplotlib"] = matplotlib
    except ImportError:
        pass

    try:
        import control
        exec_globals["control"] = control
    except ImportError:
        pass

    # Convenience math imports
    try:
        from cmath import phase, polar, rect
        import math
        exec_globals["math"] = math
        exec_globals["phase"] = phase
        exec_globals["polar"] = polar
        exec_globals["rect"] = rect
        exec_globals["pi"] = math.pi
        exec_globals["e"] = math.e
        exec_globals["j"] = 1j
    except ImportError:
        pass

    return exec_globals


def execute_code(code: str) -> tuple[str, str, list[str]]:
    """
    Execute Python engineering code and capture output + plots.
    
    Args:
        code: Python code string to execute
        
    Returns:
        tuple: (stdout_output, error_output, list_of_base64_plot_images)
    """
    stdout_capture = io.StringIO()
    error_output = ""
    plot_images = []

    exec_globals = _build_exec_globals()
    plt.close("all")

    try:
        with contextlib.redirect_stdout(stdout_capture):
            exec(code, exec_globals)  # noqa: S102

        # Capture any matplotlib figures
        for fig_num in plt.get_fignums():
            fig = plt.figure(fig_num)
            buf = io.BytesIO()
            fig.savefig(buf, format="png", dpi=120, bbox_inches="tight",
                       facecolor="white", edgecolor="none")
            buf.seek(0)
            img_b64 = base64.b64encode(buf.read()).decode("utf-8")
            plot_images.append(img_b64)
            plt.close(fig)

    except Exception:
        error_output = traceback.format_exc()
    finally:
        plt.close("all")

    return stdout_capture.getvalue(), error_output, plot_images


def extract_code_blocks(text: str) -> list[str]:
    """
    Extract Python code blocks from markdown-formatted AI response.
    
    Args:
        text: Markdown text possibly containing ```python ... ``` blocks
        
    Returns:
        List of code strings
    """
    import re
    pattern = r"```(?:python|py)\n(.*?)```"
    blocks = re.findall(pattern, text, re.DOTALL)
    return [block.strip() for block in blocks]
